services:
  db:
    image: postgres:15-alpine
    container_name: course_sphere_db
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: coursesphere_db
    
    ports:
      - "5432:5432"
    
    volumes:
      - ./backend/src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - course_sphere_db_data:/var/lib/postgresql/data

volumes:
  course_sphere_db_data: